# Generated by Django 2.2.11 on 2020-12-02 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0003_auto_20201129_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='read',
        ),
        migrations.CreateModel(
            name='ReadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='feeds.FeedItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='readitem',
            constraint=models.UniqueConstraint(fields=('user', 'feed_item'), name='unique_read_item_per_user'),
        ),
    ]
